### ISSUE TITLE
issue "URI_MISMATCH"

### ISSUE THREAD

**Issue by xxx31fr** [karl-chan/google-drive-torrent#11]
Hello,
I installed the script, created the credentials on Google API, but, when i'm on the homepage and clicked on Login, Goge send me an error page "error 400, uri_mismatch".
I put "My-domain-namz.com/login-callback" in server.js
I don't understand what URL return I must to setup.
Can you, please help me. @karl-chan 

Thanks.

**Comment by baiguke** [comment]
I also face the same problem

**Comment by karl-chan** [comment]
Duplicate of https://github.com/karl-chan/google-drive-torrent/issues/17
