### ISSUE TITLE
Why Linux Server Cant Run

### ISSUE THREAD

**Issue by arifbillah24** [karl-chan/google-drive-torrent#12]
Show Error Here:

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.8.6
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! google-drive-torrent@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the google-drive-torrent@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the google-drive-torrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs google-drive-torrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls google-drive-torrent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/bin/google-drive-torrent/npm-debug.log

**Comment by karl-chan** [comment]
Run `npm install` and try again.
