### ISSUE TITLE
Error 400 (OAuth2 Error): redirect_uri_mismatch

### ISSUE THREAD

**Issue by zippyzeetheboss1** [karl-chan/google-drive-torrent#17]
Can anybody please help me for deploying this app to herokuapp with successful Google login.
I've been trying since last month but  I've not succeeded. Every time, I try deploy to heroku and try to login with google, I get the message as (Error: redirect_uri_mismatch).
![error](https://user-images.githubusercontent.com/36583871/38258796-d2769e84-377c-11e8-92b1-3f917b457441.PNG)
Note: I've added all the google api credentials in node.js file.

**Comment by chez14** [comment]
You need to specify the `DRIVE_REDIRECT_URI` environment variable with your own host first.

See the Readme, i got mine running normal after enabling Google+ and Google Drive API.

**Comment by edenpan** [comment]
I think you can try to config the redirect URI: http://localhost:3000/login-callback  in the google console , just the link that on your error page.

**Comment by hashanant** [comment]
same error for me I changed that in `server.js` to `https://foo.herokuapp.com:3000/login-callback` still not working anyone can help?

**Comment by karl-chan** [comment]
Please follow new `README.md`.
