### ISSUE TITLE
is this support for private torrent ?

### ISSUE THREAD

**Issue by Zecx** [karl-chan/google-drive-torrent#18]
can i download private torrent using this app ? was trying on http://aidoru-online.org , and this is my result

![image](https://user-images.githubusercontent.com/37705250/38762889-8bbce4ca-3fbb-11e8-959e-553e353117b9.png)

**Comment by karl-chan** [comment]
Not tested, you are welcome to add support yourself.

**Comment by hackevil** [comment]
where u have hosted it??

**Comment by Coherent5845** [comment]
@Zecx where u have hosted it ??
