### ISSUE TITLE
Redirect to Error page after google auth

### ISSUE THREAD

**Issue by edwin099** [karl-chan/google-drive-torrent#23]
I tried to make this on heroku. https://server972.herokuapp.com/

But it is redirecting to error page after google authentication.

Is there a solution?

**Comment by ubaid4j** [comment]
I also facing the same error

**Comment by sfamos01** [comment]
eu tambem diz algo deu errado

**Comment by karl-chan** [comment]
Possible reasons:
https://github.com/karl-chan/google-drive-torrent/issues/17
https://github.com/karl-chan/google-drive-torrent/issues/26

**Comment by kaizoku75** [comment]
im facing the same error google+ google drive api enable but still 
 redirecting to error page after google authentication
how can i fix it?
