### ISSUE TITLE
[Feature Request] Zip Folder

### ISSUE THREAD

**Issue by Hanskio** [karl-chan/google-drive-torrent#24]
I really love your project, it's really awesome to download torrent in different way. But, I got some issues for downloading multiple files or a torrent with more than one file. Maybe it would be nice if we can zipping the folder before upload it to Google Drive, so we can download it as a single file. Hope you can make this feature happens in your project. Thanks in advance. :)

**Comment by karl-chan** [comment]
Google Drive already supports downloading entire folder in zipped format. Just right click on folder > Download.
