### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by alex44444** [karl-chan/google-drive-torrent#25]
![image](https://user-images.githubusercontent.com/40324428/55277157-1d6f6d00-530e-11e9-80e0-766de3ac74f6.png)

hey can someone help me please

**Comment by GajarubanSaravanan** [comment]
> ![image](https://user-images.githubusercontent.com/40324428/55277157-1d6f6d00-530e-11e9-80e0-766de3ac74f6.png)
> 
> hey can someone help me please

type ->" npm install " 
And then after installtion type -> " npm start "
