### ISSUE TITLE
Files not being saved to Google Drive

### ISSUE THREAD

**Issue by mikan01** [karl-chan/google-drive-torrent#3]
I have been using this app for the last few days and I found a weird issue where torrent's file is not being saved in the Google Drive, particularly with certain torrent where there's only a single file in the torrent.

For ex:

`magnet:?xt=urn:btih:9f542481532138424d5c2550633d7abb01688225&dn=Gold.Rush.S07E24_SP05.HQ480p.318mb.hdtv.x264-Parkers+trail1+mp4&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fzer0day.ch%3A1337&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969`

It seems to download torrent with multiple files in it to Google Drive normally, but fails to download torrents without folders and only a single file. Please check.  Thanks~!

**Comment by karl-chan** [comment]
Thanks, fixed in latest commit.
