### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by mikan01** [karl-chan/google-drive-torrent#4]
I am getting strange redirect error post oauth screen after I select the e-mail and allows app to access my Google Drive, the app suddenly shows error screen and redirects to the default homepage.

I have deployed this app many times on heroku and on vps before, it used to work fine but now it stopped working. Please check if possible. Thanks :)

P.S. http://google-drive-torrent.herokuapp.com/ still seems to be working fine for some reason and there's only issues when we deploy a new app. 

http://imgur.com/NDPkY5S

http://imgur.com/JrK7OLf

**Comment by kxbeqiluxspam** [comment]
True, i am facing the same issue. Not able to make this code work anywhere because of that

**Comment by pidutv** [comment]
I am facing the same issue :(

**Comment by VerliererK** [comment]
enable google+ API and google drive API

**Comment by nk932714** [comment]
error after enabling google+ API & drive API

"**Sorry!  Something went wrong**"

**Comment by xxx31fr** [comment]
Hello, 
I get an error when i click on Log-in button:
<img width="737" alt="karlto" src="https://user-images.githubusercontent.com/8737328/33397800-174e190c-d54d-11e7-88b4-e47d23706b2c.png">

I don't understand how to fix the problem with uri mismatch...

Thanks for your help

**Comment by lakhobim** [comment]
still error with some thing went wrong  how to fix that thanks

**Comment by mrtaurusp** [comment]
The bug still occurs.

**Comment by DIASILEDU** [comment]
Im having this error, is there any way to fix it? Already enabled Drive and G+ API

**Comment by ChandraSumer** [comment]
Go to credentials on console.developers.google.com and add "http://localhost:3000/login-callback " to Authorised redirect URIs in the client id you created for the application.

**Comment by bodoamat-git** [comment]
> Im having this error, is there any way to fix it? Already enabled Drive and G+ API

are you sure to enabled it ?

**Comment by karl-chan** [comment]
Duplicate of https://github.com/karl-chan/google-drive-torrent/issues/17
