### ISSUE TITLE
suspended when deploy heroku

### ISSUE THREAD

**Issue by afrizaloky** [karl-chan/google-drive-torrent#44]
hi, my app always suspended when deploy to heroku. 
imo, this app break the rule from heroku. i dont know how to solve it

**Comment by drhisham-code** [comment]
same here

**Comment by afrizaloky** [comment]
Maybe this app break rules from heroku

**Comment by nk932714** [comment]
yes! p2p connection is against heroku policy. Now this repo cannot be deployed on heroku anymore.
